/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bhavesh
 */
public class BAC extends javax.swing.JFrame {

    /**
     * Creates new form BAC
     */
    public BAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BACbutton = new javax.swing.JButton();
        volume = new javax.swing.JTextField();
        hour = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        status = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Blood Alcohol Content");

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel2.setText("Drink Volume(ml)");

        jLabel3.setText("Time passed sence drinking(Hour)");

        jLabel4.setText("Weight(Kg)");

        BACbutton.setText("Calculate Blood Alcohol Content");
        BACbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACbuttonActionPerformed(evt);
            }
        });

        status.setColumns(20);
        status.setRows(5);
        jScrollPane1.setViewportView(status);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(female)
                            .addComponent(male)
                            .addComponent(BACbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(13, 13, 13)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(volume, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(hour)
                                    .addComponent(weight)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back))
                .addGap(15, 15, 15)
                .addComponent(male)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(female)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weight)
                        .addGap(7, 7, 7)))
                .addComponent(BACbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACbuttonActionPerformed
    if(gender=="M"){
    Double v=Double.parseDouble(volume.getText());
    Double w=Double.parseDouble(weight.getText());
    Double h=Double.parseDouble(hour.getText());
    Double ans=((v*0.8)/(w*6.8))-(h*0.015);
    Double rans=Math.round(ans*100.0)/100.0;
    if(rans<=0.03){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Average individual appears normal");
    }
    else if(rans>0.03 && rans<=0.06){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Mild euphoria\n" +
"Relaxation\n" +
"Joyousness\n" +
"Talkativeness\n" +
"Decreased inhibition");
    }
    else if(rans>0.06 && rans<=0.099){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Blunted feelings\n" +
"Reduced sensitivity to pain\n" +
"Euphoria\n" +
"Disinhibition\n" +
"Extraversion");
    }
    else if(rans>0.099 && rans<=0.199){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Over-expression\n" +
"Boisterousness\n" +
"Possibility of nausea and vomiting");
    }
    else if(rans>0.199 && rans<=0.30){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Nausea\n" +
"Vomiting\n" +
"Emotional swings\n" +
"Anger or sadness\n" +
"Partial loss of understanding\n" +
"Impaired sensations\n" +
"Decreased libido\n" +
"Possibility of stupor");
    }
    else if(rans>0.30 && rans<=0.40){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Stupor\n" +
"Central nervous system depression\n" +
"Loss of understanding\n" +
"Lapses in and out of consciousness\n" +
"Low possibility of death");
    }
    else if(rans>0.40 && rans<=0.50){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Severe central nervous system depression\n" +
"Coma\n" +
"Possibility of death");
    }
    else if(rans>0.50){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"High possibility of death");
    }
    
    }   
    else if(gender=="F"){
     Double v=Double.parseDouble(volume.getText());
    Double w=Double.parseDouble(weight.getText());
    Double h=Double.parseDouble(hour.getText());
    Double ans=((v*0.8)/(w*5.5))-(h*0.015);
    Double rans=Math.round(ans*100.0)/100.0;
    if(rans<=0.03){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Average individual appears normal");
    }
    else if(rans>0.03 && rans<=0.06){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Mild euphoria\n" +
"Relaxation\n" +
"Joyousness\n" +
"Talkativeness\n" +
"Decreased inhibition");
    }
    else if(rans>0.06 && rans<=0.099){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Blunted feelings\n" +
"Reduced sensitivity to pain\n" +
"Euphoria\n" +
"Disinhibition\n" +
"Extraversion");
    }
    else if(rans>0.099 && rans<=0.199){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Over-expression\n" +
"Boisterousness\n" +
"Possibility of nausea and vomiting");
    }
    else if(rans>0.199 && rans<=0.30){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Nausea\n" +
"Vomiting\n" +
"Emotional swings\n" +
"Anger or sadness\n" +
"Partial loss of understanding\n" +
"Impaired sensations\n" +
"Decreased libido\n" +
"Possibility of stupor");
    }
    else if(rans>0.30 && rans<=0.40){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Stupor\n" +
"Central nervous system depression\n" +
"Loss of understanding\n" +
"Lapses in and out of consciousness\n" +
"Low possibility of death");
    }
    else if(rans>0.40 && rans<=0.50){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"Severe central nervous system depression\n" +
"Coma\n" +
"Possibility of death");
    }
    else if(rans>0.50){
        status.setText(""+rans+"%\n"+"Alcohol Effect:\n"+"High possibility of death");
    }
    
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BACbuttonActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
    gender="M";        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
    gender="F";        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new HealthCalculator().setVisible(true);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACbutton;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea status;
    private javax.swing.JTextField volume;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables

    private String gender;
}
