/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bhavesh
 */
public class HealthCalculator extends javax.swing.JFrame {

    /**
     * Creates new form HealthCalculator
     */
    public HealthCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BMIbutton = new javax.swing.JButton();
        BMRbutton = new javax.swing.JButton();
        BACbutton = new javax.swing.JButton();
        A1Cbutton = new javax.swing.JButton();
        BSAbutton = new javax.swing.JButton();
        BFbutton = new javax.swing.JButton();
        CRbutton = new javax.swing.JButton();
        CBMbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setText("Health Calculator");

        BMIbutton.setText("Basal Mass Index");
        BMIbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMIbuttonActionPerformed(evt);
            }
        });

        BMRbutton.setText("Blood metabolic Rate");
        BMRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMRbuttonActionPerformed(evt);
            }
        });

        BACbutton.setText("Blood Alcohol Content");
        BACbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACbuttonActionPerformed(evt);
            }
        });

        A1Cbutton.setText("A1C Level");
        A1Cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1CbuttonActionPerformed(evt);
            }
        });

        BSAbutton.setText("Body Surface Area");
        BSAbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSAbuttonActionPerformed(evt);
            }
        });

        BFbutton.setText("Body Fat");
        BFbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFbuttonActionPerformed(evt);
            }
        });

        CRbutton.setText("Cholestrol Ratio");
        CRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRbuttonActionPerformed(evt);
            }
        });

        CBMbutton.setText("Calory Burned Per Minute");
        CBMbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CRbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BSAbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BACbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BMIbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BMRbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A1Cbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BFbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBMbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BMRbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(BMIbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1Cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSAbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CRbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBMbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMIbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMIbuttonActionPerformed
    new BMI().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_BMIbuttonActionPerformed

    private void BMRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMRbuttonActionPerformed
    new BMR().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_BMRbuttonActionPerformed

    private void A1CbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1CbuttonActionPerformed
    new A1C().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_A1CbuttonActionPerformed

    private void BACbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACbuttonActionPerformed
    new BAC().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_BACbuttonActionPerformed

    private void BFbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFbuttonActionPerformed
    new BF().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_BFbuttonActionPerformed

    private void BSAbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSAbuttonActionPerformed
    new BSA().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_BSAbuttonActionPerformed

    private void CRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRbuttonActionPerformed
    new CR().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_CRbuttonActionPerformed

    private void CBMbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMbuttonActionPerformed
    new CBM().setVisible(true);
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_CBMbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1Cbutton;
    private javax.swing.JButton BACbutton;
    private javax.swing.JButton BFbutton;
    private javax.swing.JButton BMIbutton;
    private javax.swing.JButton BMRbutton;
    private javax.swing.JButton BSAbutton;
    private javax.swing.JButton CBMbutton;
    private javax.swing.JButton CRbutton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
